### PR TITLE
Readded container grabbing...

### PR DESCRIPTION
**Pull request by celskeggs**
They decided that they actually CAN do a container grabber... so this is back again.

Yes, the new mode _is_ supposed to be commented out. That's not a bug.

### CODE REVIEW

**Comment by amackworth** [comment]
Also, why is it commented out? (Just curious.)

**Comment by celskeggs** [comment]
Traction is now gone: they're physically changing that. The solenoid is getting re-used.

**Comment by celskeggs** [comment]
It's commented out because it doesn't work in reality - the new container grabber design needs different auto.
I'm keeping it around because it could be helpful to not have to create the entire thing from scratch if I do decide to implement it while we're at District Champs.

**Comment by amackworth** [comment]
Ah, ok then. Ready to merge when you are.

**Comment by celskeggs** [comment]
Alright. Merge this one first, and then we'll wait a bit on the other.

**Comment by amackworth** [comment]
Alright, here we go.

**Pull request merged**
