### PR TITLE
Saturday night bugfixing.

### PR DESCRIPTION
**Pull request by celskeggs**

### CODE REVIEW

**Comment by amackworth** [comment]
Having fun, are we? :smirk:

**Comment by amackworth** [comment]
Also, other than that one clarification, this looks good to me. It has been tested on the robot, yes?

**Comment by celskeggs** [comment]
These are all tested.

**Comment by celskeggs** [comment]
(And I replied.)

**Comment by amackworth** [comment]
Would you mind resolving the merge conflict?

**Comment by celskeggs** [comment]
Yeah. I just added more fixes first.

**Comment by celskeggs** [comment]
Rebased against master. Should be mergeable once reviewed.

**Comment by amackworth** [comment]
:+1:

**Pull request merged**
