### PR TITLE
Three tote auto

### PR DESCRIPTION
**Pull request by amackworth**
Note: this is still broken right now, but it's _almost_ there. :grimacing:

### CODE REVIEW

**Comment by amackworth** [comment]
OK, we now have a mostly functioning three tote auto! :tada: 

However, there are three caveats:
1. We're way over time.
2. We have to start straight on. (i.e. inside the wall)
3. It doesn't collect the last tote consistently. (This can be probably fixed with some tuning.)

Still, this is getting pretty close. :pray:

**Comment by amackworth** [comment]
@col6y It'd be great if you could try to get the turning thing working tonight, so we can focus on optimization from here on out. Thanks!

**Comment by amackworth** [comment]
@col6y Also, I'll try to finish some optimization stuff before Monday, so we can just start testing then.

**Comment by celskeggs** [comment]
I'm leaving soon - I won't have a chance to work on it tonight. Since you won't be in on Monday, I'll work on it then.

**Comment by celskeggs** [comment]
(They've also ripped off the rollers and have been testing the clamp, so there's little that I can do.)

**Comment by amackworth** [comment]
I see. Well, I will actually be coming in on Monday (I rescheduled some things), so hopefully we can fix the turning then. In the mean time, I'll try to work on some optimization stuff tomorrow.

See you Monday!

**Comment by celskeggs** [comment]
Subsumed into #102. Closing.

**Pull request closed without merging**
