### PR TITLE
Clamp autocalibration!

### PR DESCRIPTION
**Pull request by celskeggs**

### CODE REVIEW

**Comment by amackworth** [comment]
whoaaa neat

**Comment by amackworth** [comment]
Has this been tested yet?

**Comment by celskeggs** [comment]
That help?

**Comment by amackworth** [comment]
Nice, thank you! Has this been tested?

**Comment by celskeggs** [comment]
Yes, it has.

**Comment by celskeggs** [comment]
I'm taking that to mean that I can merge.

**Pull request merged**
