### PR TITLE
Fixing deadzones

### PR DESCRIPTION
**Pull request by AidanSmith**
I increased the deadzones to .3 each. I then went and fixed a few more things I noticed.

### CODE REVIEW

**Comment by celskeggs** [comment]
Have DV check if it works.

**Comment by celskeggs** [comment]
As in, the new deadzones.

**Comment by AidanSmith** [comment]
Apparently it works now.

**Comment by AidanSmith** [comment]
This looks better. Should have no more deadzone issues.

**Comment by celskeggs** [comment]
Great.

**Pull request merged**
